env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

overrides:
  - files: ["*.ts"]
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:prettier/recommended
    plugins:
      - '@typescript-eslint'
    parser: '@typescript-eslint/parser'
